//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler.parser;

/** CUP generated class containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ID = 2;
  public static final int CLASS = 3;
  public static final int INT = 4;
  public static final int STRING = 5;
  public static final int INTLITERAL = 6;
  public static final int STRINGLITERAL = 7;
  public static final int SEMICOLON = 8;
  public static final int ASSIGN = 9;
  public static final int PLUS = 10;
  public static final int MINUS = 11;
  public static final int TIMES = 12;
  public static final int DIVIDE = 13;
  public static final int LPAREN = 14;
  public static final int RPAREN = 15;
  public static final int LBRACE = 16;
  public static final int RBRACE = 17;
  public static final int IF = 18;
  public static final int ELSE = 19;
  public static final int WHILE = 20;
  public static final int RETURN = 21;
  public static final int LT = 22;
  public static final int GT = 23;
  public static final int AND = 24;
  public static final int OR = 25;
  public static final int NOT = 26;
  public static final int TRUE = 27;
  public static final int FALSE = 28;
  public static final int VOID = 29;
  public static final int BOOL = 30;
  public static final int NEW = 31;
  public static final int THIS = 32;

  public static final String[] terminalNames = new String[] {
    "EOF", "error", "ID", "CLASS", "INT", "STRING", "INTLITERAL", 
    "STRINGLITERAL", "SEMICOLON", "ASSIGN", "PLUS", "MINUS", "TIMES", 
    "DIVIDE", "LPAREN", "RPAREN", "LBRACE", "RBRACE", "IF", "ELSE", 
    "WHILE", "RETURN", "LT", "GT", "AND", "OR", "NOT", "TRUE", "FALSE", 
    "VOID", "BOOL", "NEW", "THIS"
  };
}